# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to version of notebook image that includes start-singleuser.sh script
ARG DOCKER_NOTEBOOK_IMAGE
FROM $DOCKER_NOTEBOOK_IMAGE

# Use custom startup script
USER root

# ------------ PLACE FOR TESTING -----------------
# apt-get installs
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable && \
    apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends grass-dev* grass && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN /bin/bash -c "source /opt/JupyTEPIDE/scripts/startup/04-grass_jupyter.sh"
# ------------ END TESTING -----------------------

# Install JupyTEP IDE UI layout and enable it
RUN mkdir /home/$NB_USER/dev && \
    cd /home/$NB_USER/dev && \
    git clone -b dev --single-branch https://github.com/wasat/JupyTEPIDE.git && \
    rm -rf /home/jovyan/work/notebook_count/ && \
    fix-permissions /home/$NB_USER

COPY spawn/docker-entrypoint.sh /srv/docker-entrypoint.sh
RUN chmod 777 /srv/docker-entrypoint.sh
ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

WORKDIR /home/$NB_USER
USER $NB_USER
