# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to version of notebook image that includes start-singleuser.sh script
ARG DOCKER_NOTEBOOK_IMAGE
FROM $DOCKER_NOTEBOOK_IMAGE

# Use custom startup script
USER root

# ------------ PLACE FOR TESTING -----------------

WORKDIR /opt

# Download and install Orfeo toolbox OTB
# Standalone install
# COPY OTB-6.4.0-Linux64.run /opt/OTB-6.4.0-Linux64.run
#RUN wget --quiet http://step.esa.int/thirdparties/snaphu/1.4.2-2/snaphu-v1.4.2_linux.zip && \
#    unzip snaphu-v1.4.2_linux.zip && \
#    mv snaphu-v1.4.2_linux snaphu &&\
#    chmod 755 snaphu/bin/snaphu &&\
#    rm -rf snaphu-v1.4.2_linux.zip
#
#ENV PATH="/opt/snaphu/bin:${PATH}"

RUN cd /tmp && \
    git clone https://github.com/wasat/JupyTEPIDE.git && \
    cp -rf /tmp/JupyTEPIDE/GUI/res/jupyter/static/* "/opt/conda/lib/python3.6/site-packages/notebook/static" && \
    cd JupyTEPIDE && \
    cp -R notebooks /home/jovyan/ && \
    cd GUI && \
    jupyter nbextension install source_UI --user && \
    jupyter nbextension enable source_UI/main --sys-prefix && \
    mkdir -p /home/jovyan/.ipython/profile_default/startup && \
    find "/home/jovyan/.ipython/profile_default/startup" -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    cp /tmp/JupyTEPIDE/scripts/startup/01-otb-paths.py /home/jovyan/.ipython/profile_default/startup/01-otb-paths.py && \
    cp /tmp/JupyTEPIDE/scripts/startup/02-init-leaflet.py /home/jovyan/.ipython/profile_default/startup/02-init-leaflet.py && \
    cp /tmp/JupyTEPIDE/scripts/startup/03-import_notebook_as_module.py /home/jovyan/.ipython/profile_default/startup/03-import_notebook_as_module.py && \
    cp /tmp/JupyTEPIDE/scripts/startup/04-grass.py /home/jovyan/.ipython/profile_default/startup/04-grass.py && \
    cp /tmp/JupyTEPIDE/scripts/startup/06-auxiliary_functions.py /home/jovyan/.ipython/profile_default/startup/06-auxiliary_functions.py && \
    mkdir -p /opt/jupytepide/scripts && \
    cp /tmp/JupyTEPIDE/scripts/metadata.py /opt/jupytepide/scripts/metadata.py && \
    mkdir -p /home/jovyan/.jupytepide/conf/gui && \
    cp /tmp/JupyTEPIDE/GUI/source_UI/code_snippets.json /home/jovyan/.jupytepide/conf/gui/code_snippets.json && \
    cp -R /tmp/JupyTEPIDE /opt/ && \
    find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    fix-permissions /home/$NB_USER && \
    fix-permissions /opt

# ------------ END TESTING -----------------------

# Install JupyTEP IDE UI layout and enable it
RUN mkdir /home/$NB_USER/dev && \
    cd /home/$NB_USER/dev && \
    git clone -b dev --single-branch https://github.com/wasat/JupyTEPIDE.git && \
    rm -rf /home/jovyan/work/notebook_count/ && \
    fix-permissions /home/$NB_USER

COPY spawn/docker-entrypoint.sh /srv/docker-entrypoint.sh
RUN chmod 777 /srv/docker-entrypoint.sh
ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

WORKDIR /home/$NB_USER
USER $NB_USER
