# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# Pin to version of notebook image that includes start-singleuser.sh script
ARG DOCKER_NOTEBOOK_IMAGE
FROM $DOCKER_NOTEBOOK_IMAGE

# Use custom startup script
USER root

# ------------ PLACE FOR TESTING -----------------
#COPY "spawn/.grassrc.8888" "/home/$NB_USER/.grassrc.8888"
#
#ENV GISBASE=/usr/lib/grass74 \
#    GISRC="/home/$NB_USER/.grassrc.8888" \
#    GRASS_RENDER_IMMEDIATE=png \
#    GRASS_RENDER_TRUECOLOR=TRUE \
#    LD_LIBRARY_PATH=/usr/lib/grass74/lib:$LD_LIBRARY_PATH \
#    PYTHONPATH=/usr/lib/grass74/etc/python:$PYTHONPATH \
#    PATH=/usr/lib/grass74/bin:/usr/lib/grass74/scripts:$PATH
# ------------ END TESTING -----------------------

# Install JupyTEP IDE UI layout and enable it
RUN mkdir /home/$NB_USER/dev && \
    cd /home/$NB_USER/dev && \
    git clone -b dev --single-branch https://github.com/wasat/JupyTEPIDE.git && \
    rm -rf /home/jovyan/work/notebook_count/ && \
    fix-permissions /home/$NB_USER

COPY spawn/docker-entrypoint.sh /srv/docker-entrypoint.sh
RUN chmod 777 /srv/docker-entrypoint.sh
ENTRYPOINT ["tini", "--", "/srv/docker-entrypoint.sh"]
CMD ["start-singleuser.sh"]

RUN echo $PATH

WORKDIR /home/$NB_USER
USER $NB_USER
