# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupytepide/geospatial-notebook:ver_1.0.4

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends file && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

# Download and install ESA SNAP toolbox (with all components)
# Install and configure Snappy
RUN wget --quiet http://step.esa.int/downloads/5.0/installers/esa-snap_all_unix_5_0.sh && \
    chmod +x esa-snap_all_unix_5_0.sh && \
    /bin/bash "esa-snap_all_unix_5_0.sh" -q && \
    git clone https://github.com/bcdev/jpy.git && \
    cd /tmp/jpy  && \
    python setup.py --quiet --maven bdist_wheel > /dev/null 2>&1

USER $NB_USER

RUN mkdir .snap && \
    mkdir .snap/snap-python && \
    mkdir .snap/snap-python/snappy && \
    cp /tmp/jpy/dist/jpy-0.9.0.dev1-cp36-cp36m-linux_x86_64.whl ".snap/snap-python/snappy" && \
    cd /opt/snap/bin && \
    ./snappy-conf /opt/conda/envs/python34/bin/python && \
    cp -R /home/jovyan/.snap/snap-python/snappy /opt/conda/envs/python34/lib/python3.4/site-packages/

ENV PATH="/opt/conda/bin:${PATH}"

# Download and install Orfeo toolbox OTB
RUN wget --quiet https://www.orfeo-toolbox.org/packages/OTB-6.2.0-Linux64.run && \
    chmod +x OTB-6.2.0-Linux64.run && \
    /bin/bash -c "OTB_PYTHON_EXE=/opt/conda/envs/python27/bin/python2.7 ./OTB-6.2.0-Linux64.run" -q

USER root
RUN rm -r /tmp/*  && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

WORKDIR /home/$NB_USER
USER $NB_USER