# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupytepide/geospatial-notebook:ver_1.0.5

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
 RUN apt-get update -qq && \
     apt-get install -qqy --no-install-recommends file && \
     apt-get clean && \
     rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

# Download and install ESA SNAP toolbox (with all components)
# Install and configure Snappy
RUN wget --quiet http://step.esa.int/downloads/5.0/installers/esa-snap_all_unix_5_0.sh && \
    chmod +x esa-snap_all_unix_5_0.sh && \
    /bin/bash "esa-snap_all_unix_5_0.sh" -q && \
    git clone https://github.com/bcdev/jpy.git && \
    cd /tmp/jpy  && \
    python setup.py --quiet --maven bdist_wheel > /dev/null 2>&1

# RUN chmod 755 /opt &&\
#    chown -R $NB_USER:$NB_GID /opt

USER $NB_USER

RUN mkdir .snap && \
    mkdir .snap/snap-python && \
    mkdir .snap/snap-python/snappy && \
    cp /tmp/jpy/dist/jpy-0.9.0-cp36-cp36m-linux_x86_64.whl ".snap/snap-python/snappy" && \
    cd /opt/snap/bin && \
    ./snappy-conf /opt/conda/envs/python34/bin/python && \
    cp -R /home/jovyan/.snap/snap-python/snappy /opt/conda/envs/python34/lib/python3.4/site-packages/

ENV PATH="/opt/conda/bin:${PATH}"

USER root
WORKDIR /opt
# Download and install Orfeo toolbox OTB
# Standalone install
RUN wget --quiet https://www.orfeo-toolbox.org/packages/OTB-6.4.0-Linux64.run && \
    #cp "/tmp/OTB-6.4.0-Linux64.run" "/opt/OTB-6.2.0-Linux64.run"  && \
    chmod +x OTB-6.4.0-Linux64.run && \
    /bin/bash -c "OTB_PYTHON_EXE=/opt/conda/envs/python27/bin/python2.7 ./OTB-6.4.0-Linux64.run" -q &&\
    mkdir -p /home/jovyan/.ipython/profile_default/startup && \
    wget --quiet -O /home/jovyan/.ipython/profile_default/startup/01-otb-paths.py https://raw.githubusercontent.com/wasat/JupyTEPIDE/master/scripts/startup/01-otb-paths.py && \
    rm -r OTB-6.4.0-Linux64.run

# Install JupyTEP IDE UI layout and enable it
RUN rm -r /tmp/*  && \
    cd /tmp && \
    git clone https://github.com/wasat/JupyTEPIDE.git && \
    cd JupyTEPIDE && \
    cp -R notebooks /home/jovyan/ && \
    cd GUI && \
    jupyter nbextension install source_UI --user && \
    jupyter nbextension enable source_UI/main --sys-prefix && \
    rm -rf JupyTEPIDE

RUN rm -r /tmp/*  && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    fix-permissions "/opt/OTB-6.4.0-Linux64"

WORKDIR /home/$NB_USER
USER $NB_USER