# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupytepide/pyaddons-notebook

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# mc
RUN apt-get update -qq && \
    apt-get install -qy --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_USER

# Conda installs
RUN conda install --yes -c conda-forge \
    'libgdal' \
    'gdal' \
    'owslib' \
    'geopandas' \
    'fiona' \
    'shapely' \
    'geopy' \
    'geojson' \
    'gridgeo'&& \
    fix-permissions $CONDA_DIR

USER $NB_USER