# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/scipy-notebook

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# mc
RUN apt-get update && \
    apt-get install -y --no-install-recommends mc nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_USER

# Conda installs
RUN conda install --quiet --yes -c conda-forge \
    'jupyter_nbextensions_configurator' &&  \
    # Activate ipywidgets extension in the environment that runs the notebook server
    jupyter nbextensions_configurator enable --user && \
    fix-permissions $CONDA_DIR

# Install facets which does not have a pip or conda package at the moment
RUN cd /tmp && \
    git clone https://github.com/wasat/JupyTEPIDE.git && \
    cd JupyTEPIDE && \
    cp -r notebooks/* /home/jovyan && \
    cd GUI && \
    jupyter nbextension install source_UI --user && \
    jupyter nbextension enable source_UI/main --sys-prefix && \
    rm -rf JupyTEPIDE && \
    fix-permissions $CONDA_DIR

USER $NB_USER