# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupytepide/geospatial-notebook

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# mc
RUN apt-get update -qq && \
    apt-get install -qy --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create a Python 3.4 environment using conda including at least the ipython kernel
# and the kernda utility. Add any additional packages you want available for use
# in a Python 3.4 notebook to the first line here (e.g., pandas, matplotlib, etc.)
RUN conda create --quiet --yes -p $CONDA_DIR/envs/python34 python=3.4 ipython ipykernel && \
    conda clean -tipsy

USER root

# Create a global kernelspec in the image and modify it so that it properly activates
# the python2 conda environment.
RUN $CONDA_DIR/envs/python34/bin/python -m ipykernel install && \
    /bin/bash -c "source activate python34"

USER $NB_USER