# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
ARG DOCKER_VER
FROM jupytepide/geospatial-notebook:$DOCKER_VER

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
RUN apt-get update -qq && \
    apt-get install -qqy --no-install-recommends --allow-unauthenticated file && \
    apt-get clean  && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV JDK_HOME /usr/lib/jvm/java-8-oracle

WORKDIR home/$NB_USER

# Download and install ESA SNAP toolbox (with all components)
# Install and configure Snappy
COPY esa-snap_all_unix_6_0.sh /home/$NB_USER/esa-snap_all_unix_6_0.sh
#RUN wget --quiet http://step.esa.int/downloads/6.0/installers/esa-snap_all_unix_6_0.sh && \
RUN chmod +x /home/$NB_USER/esa-snap_all_unix_6_0.sh

USER $NB_USER
WORKDIR home/$NB_USER
RUN  /bin/bash "/home/$NB_USER/esa-snap_all_unix_6_0.sh" -q
    # fix-permissions /opt/snap
#    git clone https://github.com/bcdev/jpy.git && \
#    cd /tmp/jpy  && \
#    python setup.py --quiet --maven bdist_wheel > /dev/null 2>&1

RUN mkdir /home/$NB_USER/snap/snap-python && \
    mkdir /home/$NB_USER/snap/snap-python/snappy && \
#   cp /tmp/jpy/dist/jpy-0.9.0-cp36-cp36m-linux_x86_64.whl ".snap/snap-python/snappy" && \
    wget https://github.com/wasat/JupyTEPIDE/raw/dev/libs/jpy-0.9.0-cp36-cp36m-linux_x86_64.whl -P "/home/$NB_USER/snap/snap-python/snappy"

WORKDIR home/$NB_USER/snap/bin
RUN cd /home/$NB_USER/snap/bin && \
    ./snappy-conf /opt/conda/bin/python /home/jovyan/snap/snap-python && \
    #  ./snappy-conf /home/daniel/anaconda3/bin/python /home/daniel/snap/snappy
    cp -R /home/jovyan/snap/snap-python/snappy /opt/conda/lib/python3.6/site-packages/

ENV PATH="/opt/conda/bin:${PATH}"

USER root
WORKDIR /opt
# Download and install Orfeo toolbox OTB
# Standalone install
RUN wget --quiet https://www.orfeo-toolbox.org/packages/OTB-6.4.0-Linux64.run && \
    #cp "/tmp/OTB-6.4.0-Linux64.run" "/opt/OTB-6.2.0-Linux64.run"  && \
    chmod +x OTB-6.4.0-Linux64.run && \
    /bin/bash -c "OTB_PYTHON_EXE=/opt/conda/envs/python27/bin/python2.7 ./OTB-6.4.0-Linux64.run" -q &&\
    rm -rf OTB-6.4.0-Linux64.run
# Install JupyTEP IDE UI layout and enable it
# RUN rm -r /tmp/*  && \
#    cd /tmp && \
#    git clone https://github.com/wasat/JupyTEPIDE.git && \
#    cd JupyTEPIDE && \
#    cp -R notebooks /home/jovyan/ && \
#    cd GUI && \
#    jupyter nbextension install source_UI --user && \
#    jupyter nbextension enable source_UI/main --sys-prefix && \
#    mkdir -p /home/jovyan/.ipython/profile_default/startup && \
#    cp /tmp/JupyTEPIDE/scripts/startup/01-otb-paths.py /home/jovyan/.ipython/profile_default/startup/01-otb-paths.py && \
#    cp /tmp/JupyTEPIDE/scripts/Leaflet/__init__.py /home/jovyan/.ipython/profile_default/startup/02-init-leaflet.py && \
#    rm -rf JupyTEPIDE
RUN find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER && \
    fix-permissions "/opt/OTB-6.4.0-Linux64"

WORKDIR /home/$NB_USER
USER $NB_USER