# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
ARG DOCKER_VER
FROM jupytepide/scipy-ext-notebook:$DOCKER_VER

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable && \
    apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends grass-dev* grass && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER $NB_USER

# Conda installs
RUN conda install --quiet --yes -c conda-forge \
    'libgdal=2.2.3*' \
    'gdal=2.2.3*' \
    'shapely=1.6.3*' \
    'fiona=1.7.10*' \
    'geojson=2.3.0' \
    'geopandas=0.3.0*' \
    'geopy=1.11.0*' \
    'gridgeo=0.2.1*' \
    'owslib=0.16.0*' && \
     conda clean -tipsy

USER root

RUN find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    npm cache clean && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

WORKDIR /home/$NB_USER
USER $NB_USER