# Copyright (c) JupyTEP IDE Development Team.
# Distributed under the terms of the Modified BSD License.
ARG DOCKER_VER
FROM jupytepide/science-notebook:$DOCKER_VER

LABEL maintainer="JupyTEP IDE Project <jupytep@wasat.pl>"

USER root

# apt-get installs
RUN add-apt-repository ppa:ubuntugis/ubuntugis-unstable && \
    apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends grass-dev* grass && \
    apt-get autoremove -qq && \
    apt-get clean -qq && \
    rm -rf /var/lib/apt/lists/*

# --------------- Configuration Grass GIS -------------------
COPY "scripts/.grassrc.8888" "/home/$NB_USER/.grassrc.8888"

ENV GISBASE=/usr/lib/grass74 \
    GISRC="/home/$NB_USER/.grassrc.8888" \
    GRASS_RENDER_IMMEDIATE=png \
    GRASS_RENDER_TRUECOLOR=TRUE \
    LD_LIBRARY_PATH=/usr/lib/grass74/lib:$LD_LIBRARY_PATH \
    PYTHONPATH=/usr/lib/grass74/etc/python:$PYTHONPATH \
    PATH=/usr/lib/grass74/bin:/usr/lib/grass74/scripts:$PATH
# ------------------------------------------------------------

USER $NB_USER

# Conda installs
RUN conda install --quiet --yes -c conda-forge \
    'libgdal=2.2.3*' \
    'gdal=2.2.3*' \
    'shapely=1.6.3*' \
    'fiona=1.7.10*' \
    'geoalchemy2=0.4.*' \
    'geojson=2.3.0' \
    'geopandas=0.3.0*' \
    'geopy=1.11.0*' \
    'gridgeo=0.2.1*' \
    'owslib=0.16.0*' && \
     conda install --quiet --yes -c mrterry -n python27 mapnik && \
     conda clean -tipsy && \
     /bin/bash -c "source activate python27 && pip install -q --no-cache-dir mapnik && conda clean -tipsy && source deactivate python27"

USER root

RUN find /tmp -mindepth 1 -maxdepth 1 -print0 | xargs -0 rm -rf && \
    npm cache clean --force && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

WORKDIR /home/$NB_USER
USER $NB_USER